export const ErrorCodes = {
  SERVER_ERROR: 'ERR-500',
  BAD_REQUEST: 'ERR-400',
  NOT_FOUND: 'ERR-404',
  CONFLICT: 'ERR-409',
  UNAUTHORIZED: 'ERR-401',

  AUTH_INVALID_CREDENTIALS: 'ERR-AU001',

  CREATE_USER: 'ERR-U001',
  UPDATE_USER: 'ERR-U002',
  DELETE_USER: 'ERR-U003',
  DUPLICATE_USER: 'ERR-U004',
};
